### ISSUE TITLE
Crashs at starting

### ISSUE THREAD

**Issue by TheButterbrotMan** [MUYUTwilighter/saplanting_fabric#1]
https://bytebin.lucko.me/CZYtfQwDoL

**Comment by MUYUTwilighter** [comment]
Seems that package "org.json" add by me is somehow disabled by other mods, I tested on my client game and it works fine.
Still not clear about which mods exactly caused this.
I'll might "gson" instead in later version(not 1.1-alpha-2, this version still use org.json)

**Comment by MUYUTwilighter** [comment]
Found the bug, when IDEA assemble my project, it ignore the package "org.json" that should be packed into my mod.
There is no problem in version "1.1-alpha-2", just update it and this problem might not happen again.

Please inform me if no similar crash happen again, so that I will close this issue page.

**Comment by MUYUTwilighter** [comment]
Try "saplanting-fabric-1.18-1.1-alpha-3"
I fixed that in this version. I've tested and it works fine now.
If you see this message, try update the mod and reply here if your minecraft works fine, so that I can choose whether close this issue or keep on fixing it.
If no reply, this issue will be closed in 2 days.
